name: Example project build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - run: sudo apt-get remove scala-library scala
    - run: sudo wget www.scala-lang.org/files/archive/scala-2.12.11.deb
    - run: sudo dpkg -i scala-2.12.11.deb
    - run: scala -version
    - run: echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    - run: sudo apt-get update
    - run: sudo apt-get install sbt
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - run: (cd examples/rdd-colocation-mining;sbt clean assembly;java -jar target/scala-2.12/*.jar)
    - run: (cd examples/sql;sbt clean assembly;java -jar target/scala-2.12/*.jar)
    - run: (cd examples/viz;sbt clean assembly;java -jar target/scala-2.12/*.jar)
