name: Scala and Java build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        spark: [2.4.7, 3.0.2, 3.1.1]
        scala: [2.11.8, 2.12.8]
        exclude:
          - spark: 3.1.1
            scala: 2.11.8
          - spark: 3.0.2
            scala: 2.11.8

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: git submodule update --init --recursive # Checkout Git submodule if necessary
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SCALA_VERSION: ${{ matrix.scala }}
      run: if [ ${SPARK_VERSION:0:1} == "3" ]; then mvn -q clean install -Dscala=${SCALA_VERSION:0:4} -Dspark=3.0 ; else mvn -q clean install -Dscala=${SCALA_VERSION:0:4} -Dspark=2.4 ; fi
    - run: mkdir staging
    - run: cp core/target/sedona-*.jar staging
    - run: cp sql/target/sedona-*.jar staging
    - run: cp viz/target/sedona-*.jar staging
    - run: cp python-adapter/target/sedona-*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: generated-jars
        path: staging
